# MarkPrompter Themes Configuration

[[themes]]
name = "Light"
background_color = [240, 240, 245]
text_color = [60, 60, 70]
heading_colors = [
    [100, 100, 180], # H1
    [90, 90, 170],   # H2
    [80, 80, 160],   # H3
    [70, 70, 150],   # H4
    [60, 60, 140],   # H5
    [50, 50, 130],   # H6
]

[[themes]]
name = "Dark"
background_color = [40, 44, 52]
text_color = [220, 223, 228]
heading_colors = [
    [255, 180, 100], # H1
    [230, 160, 90],  # H2
    [210, 140, 80],  # H3
    [190, 120, 70],  # H4
    [170, 100, 60],  # H5
    [150, 80, 50],   # H6
]

[[themes]]
name = "Solarized"
background_color = [0, 43, 54]
text_color = [131, 148, 150]
heading_colors = [
    [181, 137, 0],   # H1
    [203, 75, 22],   # H2
    [220, 50, 47],   # H3
    [211, 54, 130],  # H4
    [108, 113, 196], # H5
    [38, 139, 210],  # H6
]

[[themes]]
name = "Forest"
background_color = [31, 42, 35]
text_color = [200, 220, 200]
heading_colors = [
    [138, 201, 38], # H1
    [118, 181, 28], # H2
    [98, 161, 18],  # H3
    [78, 141, 8],   # H4
    [58, 121, 0],   # H5
    [38, 101, 0],   # H6
]

[[themes]]
name = "Sepia"
background_color = [240, 228, 200]
text_color = [70, 48, 28]
heading_colors = [
    [128, 80, 32],  # H1
    [118, 70, 32],  # H2
    [108, 60, 32],  # H3
    [98, 50, 32],   # H4
    [88, 40, 32],   # H5
    [78, 30, 32],   # H6
]
